### ISSUE TITLE
Build instructions don't work

### ISSUE THREAD

**Issue by koto** [google/end-to-end#171]
_From [ddascale...@gmail.com](https://code.google.com/u/118325916191112457643/) on August 20, 2014 09:02:03_

**Steps to reproduce:**  
1. git clone https://code.google.com/p/end-to-end.build/  
2. cd end-to-end.build/  
3. ./do.sh install_deps # everything succeeds  
4. ./do.sh build_extension  

**What happens?**  

Error message "Download libraries needed to build first. Use ./do.sh install_deps.", despite having just run `./do.sh install_deps`. sudo didn't help.  

_Original issue:_ http://code.google.com/p/end-to-end/issues/detail?id=134

**Comment by sideshowbarker** [comment]
On my OSX system `./do.sh build_extension` failed because it couldn't find `lib/closure-compiler/build/compiler.jar`. And that was because I didn't have JAVA_HOME set.

So I think the https://github.com/google/end-to-end/wiki/Build-instructions page should have a mention/reminder that the JAVA_HOME environment variable needs to be set.

**Comment by koto** [comment]
I can build the extension without JAVA_HOME on OSX:

```
$ env | grep -c JAVA_HOME
0
```
Was there a compiler.jar file in the first place?

**Comment by sideshowbarker** [comment]
> I can build the extension without JAVA_HOME on OSX:

Doesn't OSX only have Java 6 by default? And if you don't install Java 7 and have JAVA_HOME pointed to it, then doesn't it try to just use Java 6 but then fail (silently)?

> Was there a compiler.jar file in the first place? It's built with ant during ./do.sh install_deps.

Yeah it didn't build it when I ran `./do.sh install_deps`. I think the reason is that without JAVA_HOME set, it does what I described above (it tries to use Java 6 but fails).

**Comment by koto** [comment]
Yes, Java 7 is required, and on OSX you have to install it separately. 

I think I found it: ./do.sh install_deps did not check for java presence nor its version. I added that check directly in #209. Once it's merged, it should be all fine. Thanks for reporting!

**Comment by sideshowbarker** [comment]
> I think I found it: ./do.sh install_deps did not check for java presence nor its version. I added that check directly in #209.

Cool, looks good

> Once it's merged, it should be all fine. Thanks for reporting!

Glad to help. Thanks for fixing it, and thanks for your work on end-to-end—I appreciate having it and look forward to seeing it develop further.
