### ISSUE TITLE
backup key window abort key missing

### ISSUE THREAD

**Issue by JimLoose** [google/end-to-end#224]
![bild 2015-01-28 um 10 26 58](https://cloud.githubusercontent.com/assets/195000/5936389/7b82863c-a6e4-11e4-9eb4-82afac010d50.png)

there is no possibility to leave this window!

I like the idea, but usability + setup is incredible bad!!
Btw. this looks like a part-time-one-day-a-week project of Google?

**Comment by rcchan** [comment]
Problem is related to overlay.js:51 `goog.dom.removeNode(goog.dom.getElementByClass('modal-dialog-title-close', elem));` which removes the close button from all `Overlay` dialogs.

Potential solution could be for `RestoreKey` to inherit directly from `Dialog` or to create a cancel button with `this.setButtonSet(goog.ui.Dialog.ButtonSet.createOkCancel());` in `decorateInternal`.

I would submit a PR for this except that I can't build extension due to #264
