### ISSUE TITLE
Clicking outside of compose dialog loses message/changes

### ISSUE THREAD

**Issue by rcchan** [google/end-to-end#275]
When using the compose dialog (clicking the extension icon near the address bar) changes are lost if the user mistakenly clicks outside the dialog.

This is the case for both new messages and modifying existing encrypted drafts.

The dialog should do one or more of the following:
* Remember the message text between uses (click off, click back on, data still there)
* Automatically save as encrypted draft
  * Possibly unwanted since it leaks the fact that the user is in the process of composing a message
  * Might be a good option or default if a draft already exists
* At least issue a warning confirmation that the changes will be lost.

**Comment by adhintz** [comment]
There's supposed to be an encrypted draft feature. For references to it,
search for canSaveDraft
https://github.com/google/end-to-end/search?utf8=%E2%9C%93&q=canSaveDraft

**Comment by rcchan** [comment]
That feature is enabled and working but requires manual interaction to hit save.
The issue I have is that if I click off the compose window before doing so (possibly accidentally) then my message is gone.

**Comment by koto** [comment]
You can use the popout feature (icon in the top right corner) to have a persistent window, that does not disappear on click out. 

canSaveDraft is about saving the draft message in the web application. We dropped the support for storing the message in the local storage, because it was brittle when the extension is used with multiple windows of multiple origins. With the popout you can have several simultaneous compose/decrypt/etc windows and each of them is tied to the originating browser tab..

**Comment by rcchan** [comment]
It still seems like a way for the user to inadvertently lose a message if the parent window were closed.

At the very least, I would still suggest a confirmation of discarding unsaved changes and/or updating the message draft in the web application if one already exists (if I opened a draft, made edits, and close the window without hitting save draft again)

**Comment by daveloyall** [comment]
Here's my user story:

From a gmail (GAFYD) tab, I clicked the end-to-end button and began writing a medium length email to a friend.  I wanted to include some hyperlink, so I hit `ctrl+t` in the middle of a sentence so that I could perform a web search.

Of course, the message was irrevocably lost.

That's a bug.  One common combo key should not destroy a long message, without so much as a prompt.

The simplest solution, in my mind, is to simply not destroy the message widget (the one attached to the button) when I switch tabs.  By whatever method you prefer.  Maybe pop it out, if Chrome doesn't support per-tab button danglers?

**Comment by koto** [comment]
There's nothing we can do about it unfortunately. Extension popups cannot survive tab navigation, and we will not render something within a page (Gmail in this regard), like e.g. Mailvelope, because of security. See our Threat model in the wiki for more info about our reasoning.

One feature you could use to survive clicking away is a 'popout' (click the second rightmost icon in the extension window). That one opens a new window and this one will be persistent. Give it a try. Unfortunately in Chrome extension we can't do much more for the usability without compromising the security of our solution.

**Comment by daveloyall** [comment]
I'm interested in asking the Chromium team about it, but I'm not sure which folks would be interested in this very specific issue.  Any ideas?

**Comment by koto** [comment]
crbug.com has a special label for extensions: `Cr-Platform-Extensions-API`. But I don't think this issue would be addressed, as the popup window is meant to be destroyed on focus change. Other extension get around with using the website DOM for persisting the UI, but we have totally different security considerations.

**Comment by daveloyall** [comment]
Well, if we're to imagine e2e becoming a popular thing used daily by many users, then this will have to be addressed somehow.  I'm sure you are on top of that.  Perhaps this is an app-vs-extension issue.

"The computer ate my email" isn't tolerable these days... :)

Anyway, thank you for the feedback and advice about the crbug.com tag.

**Comment by daveloyall** [comment]
Chrome Sidebars: https://code.google.com/p/chromium/issues/detail?id=477424

**Comment by mjperrone** [comment]
I had this problem, and started using popout exclusively. It's pretty annoying to have to click it every time. I think this should be an option where you can have it pop out by default. Feature request here #356.
