### ISSUE TITLE
Integrate keylookup with current Facebook PGP

### ISSUE THREAD

**Issue by fpietrosanti** [google/end-to-end#297]
Facebook now do support importing a PGP public key, that's then being used for encrypting notifications.

If Google end to end do support key lookup, it would be nice to support key lookup trough Facebook:

https://www.facebook.com/notes/protect-the-graph/securing-email-communications-from-facebook/1611941762379302

**Comment by koto** [comment]
Is the PGP public key discoverable by anyone else than the users themselves? I don't see OpenPGP public key support in FB API yet - https://developers.facebook.com/docs/graph-api/reference/user.

**Comment by webhat** [comment]
It's not discoverable, also they currently don't support ECDSA which means you need to go outside end-to-end to generate keys.

**Comment by OmgImAlexis** [comment]
[Keybase](https://keybase.io/) would also be nice and their keys are all public. Here's their [api](https://keybase.io/docs/api/1.0) page.

**Comment by jalcine** [comment]
I think it's fair to say that Facebook can't be used as a key retrieval store for end-to-end. As @OmgImAlexis has mentioned, [Keybase](https://keybase.io) has more potential than Facebook.

**Comment by jalcine** [comment]
Thus, making this issue moot.

**Comment by tanx** [comment]
> Is the PGP public key discoverable by anyone else than the users themselves? I don't see OpenPGP public key support in FB API yet - https://developers.facebook.com/docs/graph-api/reference/user.

Not yet. One can only hope that they expose a HKP interface. Would be a good source of public keys since facebook can authenticate email address ownership and obviously has a huge user base.

> Keybase would also be nice and their keys are all public. Here's their api page.

Unfortunately keybase does not support api queries via email address, since they cannot publicly verify email address ownership like twitter or dns. I asked the developers and they are thinking about adding support, although it wasn't clear yet how the authentication would work.

**Comment by sirdarckcat** [comment]
let's wait for facebook to use an API we can depend on (as they mentioned this was a workaround)
