### ISSUE TITLE
UI should not display "back up code" when only imported keys exist.

### ISSUE THREAD

**Issue by daveloyall** [google/end-to-end#302]
Hi.

What is this "back up code", seen on the settings.html (Options) interface?

Since this should be a bug report, not a question: The documentation is missing information about this "back up code". :)

**Comment by daveloyall** [comment]
Also, whatever it is.. it doesn't seem to be very long!  Couldn't it be brute-forced?

**Comment by koto** [comment]
Backup code is a representation of a RNG seed that was used to generate the private keys.https://github.com/google/end-to-end/blob/master/src/javascript/crypto/e2e/openpgp/keyring.js#L292  With it, you can regenerate the same exact private key(s). It carries 128 bit entropy, so you're welcome to bruteforce it ;)

**Comment by daveloyall** [comment]
Wow, you must have found a new way to store bits!
![capture](https://cloud.githubusercontent.com/assets/1524866/7924463/f480b74a-0880-11e5-8a92-83b8ba63f1e5.PNG)

;)

I think I know what happened.  I didn't generate keys, I imported them.  So perhaps my 128 bits were never generated and stored?

Ah, yes, it's a couple of null bytes.

    hobbes@metalbaby:~$ echo AAA= | base64 -d |hexdump 
    0000000 0000                                   
    0000002

Something sounds wrong about storing the seed value.  Sounds like the generator is just a dictionary with 2^128 entries.  That's a lot!  But, doesn't it mean that a clever user could eliminate N of the M possible keypairs?  Am I wrong that M is supposed to be larger than 2^128?

I guess there's nothing wrong with storing the seed value, though it's important to note that, for all intents and purposes, the value *is* the private key. (So long as the generator is available.)

Anyway, that stuff is above my head.  I'm changing the title of this ticket.  This ticket is now about the AAA=, not the back up codes in general.

**Comment by koto** [comment]
You're correct - the seed should be protected, just like a private key (that's why we also encrypt the seed if the user chose to protect his keyring with a passphrase). 128 bits of security for the seed is [OK](http://security.stackexchange.com/questions/6141/amount-of-simple-operations-that-is-safely-out-of-reach-for-all-humanity/6149#6149), other algorithms used in OpenPGP won't give you much more (e.g. we use AES-128 for the symmetric encryption).

Good finding with the 'null' seed. You're right, we only generate the seed when first key is generated, so we should not present the backup code at all in your case. That's a valid bug.
