### ISSUE TITLE
"it is not yet ready for general use" roadmap

### ISSUE THREAD

**Issue by techtonik** [google/end-to-end#362]
Is there a plan what is needed to make it available from webstore?

**Comment by chrisjonesfpu** [comment]
I agree totally. This project needs a road map and some dates for target.
Severely.

Otherwise, I can see this being nothing but a crypto project that just gets
slogged away at for years and gets forgotten about until some better and
more complete comes along and replaces it.


Regards,

Chris Jones

On Sun, Jan 17, 2016 at 7:01 PM, anatoly techtonik <notifications@github.com

**Comment by adhintz** [comment]
Thank you for the feedback and I agree that a clear roadmap would help improve the project. However unfortunately there is no roadmap nor date commitments that we have available to share, nor do I expect us to have one available in the immediate future. I'll close this issue, but please feel free to continue the discussion on our mailing list: https://groups.google.com/forum/#!forum/e2e-discuss

**Comment by techtonik** [comment]
https://groups.google.com/d/msg/e2e-discuss/WuA5PQljtoQ/z1G2BnLHAwAJ
